### ISSUE TITLE
Bundle ffmpeg so exporting works out of the box

### ISSUE THREAD

**Issue by pizzadude** [snapcrafters/opentoonz-morevna#5]
Hi, currently, in order to export, I have to download the static linux build of ffmpeg and put it in ~/snap/opentoonz-morevna/current/ffmpeg/ and then point to that path in OpenToonz settings. Instead, you should probably bundle ffmpeg with the snap.

Otherwise, in my initial testing, it works fine on Fedora 31 KDE whereas the official AppImage version crashed on launch.

**Comment by pizzadude** [comment]
wait nvm it looks like ffmpeg is bundled but it isn't detected by the program?

**Comment by its-thomas** [comment]
@pizzadude See my former post: [Snap version on Lubuntu: FFmpeg path not recognized](https://github.com/opentoonz/opentoonz/issues/2578)

While I am using Debian 10 instead of Lubuntu now and furthermore the flatpak version of vanilla OpenToonz, where this is issue is fixed and the ffmpeg is properly detected at its system path at `/usr/bin`, the Snap version of OT Morevna (no flatpak version available here) does unfortunately still suffer from the same problem and gives me the following error message:

"FFmpeg not found, please set the location in the Preferences and restart."

**Comment by merlijn-sebrechts** [comment]
The `ffmpeg` shipped in this snap was broken. This PR fixes that issue and includes some magic to automatically set the correct preferences option so ffmpeg is found by default: https://github.com/snapcrafters/opentoonz-morevna/pull/9
